### ISSUE TITLE
Get i18n rolling

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SummaryCards#1]
- [x] add repo to user group with push rights
- [x] review en.json and qqq.json
- [x] ping twn to add the repo
- [x] affirmation by twn that support was added

**Comment by JeroenDeDauw** [comment]
I'm happy to provide you with this very useful rolling bunny picture.

![rolling-bunny](https://cloud.githubusercontent.com/assets/146040/15747489/431ee928-28db-11e6-8e33-229532bb54b1.jpg)

**Comment by kghbln** [comment]
@Nikerabbit @siebrand Heiya, another extension ready for tw.n Thanks and cheers

**Comment by Nikerabbit** [comment]
Done.

**Comment by kghbln** [comment]
> Done.

Cool. Thanks!

**Comment by Nikerabbit** [comment]
It's not working:

```
cd /resources/nike/mwgithub/SemanticMediaWiki/SummaryCards; git add .; if git commit -m 'Localisation updates from https://translatewiki.net.'; then git push origin 'master'; fi
[Mon Jun 13 07:54:40 2016] [hphp] [15814:7fd045c7ae40:0:000001] [] 
Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\ProcessFailedException' with message 'The command "cd /resources/nike/mwgithub/SemanticMediaWiki/SummaryCards; git add .; if git commit -m 'Localisation updates from https://translatewiki.net.'; then git push origin 'master'; fi" failed.

Exit Code: 128(Invalid exit argument)

Working directory: /resources/nike

Output:
================
[master fbe3f15] Localisation updates from https://translatewiki.net.
 11 files changed, 124 insertions(+), 2 deletions(-)
 create mode 100644 i18n/bn.json
 create mode 100644 i18n/de.json
 create mode 100644 i18n/es.json
 create mode 100644 i18n/fr.json
 create mode 100644 i18n/gl.json
 create mode 100644 i18n/id.json
 create mode 100644 i18n/ko.json
 create mode 100644 i18n/ksh.json
 create mode 100644 i18n/mk.json
 create mode 100644 i18n/zh-hans.json


Error Output:
================
ERROR: Permission to SemanticMediaWiki/SummaryCards.git denied to Nikerabbit.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
' in /resources/nike/translatewiki/repong/vendor/symfony/process/Process.php:226
Stack trace:
#0 /resources/nike/translatewiki/repong/repong.php(136): Symfony\Component\Process\Process->mustRun()
#1 /resources/nike/translatewiki/repong/repong.php(192): RepoNg->commit()
#2 {main}
```

**Comment by kghbln** [comment]
Oops, obviously the repo has to be added to the group as well. This is done now, so there should not be any further worries. While I was at it I also added [Semantic Scribunto](https://github.com/SemanticMediaWiki/SemanticScribunto/issues/1). Sorry and thank you!

**Comment by Nikerabbit** [comment]
You should be seeing a commit on this Thursday then.

**Comment by kghbln** [comment]
Cool and thank you!
